### PR TITLE
[Draft, Refact] Deprecate constructors

### PR DESCRIPTION
**Pull request by jpmoutinho**
To be merged after https://github.com/pasqal-io/qadence-libs/pull/8

### CODE REVIEW

**Review by dominikandreasseitz — APPROVED** [review]
I guess this warnings will not be seen by qdevs who develop locally. didnt we use something like UserWarning at some point? @awennersteen

**Comment by jpmoutinho** [comment]
> I guess this warnings will not be seen by qdevs who develop locally. didnt we use something like UserWarning at some point? @awennersteen

Why not? They show in notebooks

**Comment by awennersteen** [comment]
They'll show I think as the default log level in Python is warning.
However, I think the best practise is to use the warnings module, see e.g. this stackoverflow:

https://stackoverflow.com/a/72285990

**Comment by Roland-djee** [comment]
LGTM. I think this is fine now. However, for future reference, we should keep in mind using the `warnings` module as suggested @awennersteen.

**Review by Roland-djee — APPROVED** [review]

**Comment by Roland-djee** [comment]
It is mergeable now @jpmoutinho ? Since the other is merged.

**Comment by jpmoutinho** [comment]
@Roland-djee I do mean to make the changes to the warnings here, and also wanted to sync with you about the qadence-libs in general before merging.

**Comment by Roland-djee** [comment]
> @Roland-djee I do mean to make the changes to the warnings here, and also wanted to sync with you about the qadence-libs in general before merging.

Sure thing.

**Pull request closed without merging**
