### PR TITLE
[Performance] Expand PyQComposedBlock to 2 qubit gates

### PR DESCRIPTION
**Pull request by ducthanh1991**
Closes https://github.com/pasqal-io/qadence/issues/40

list of changes:

**1. Added `grouped_operations()` method**
The method outputs a list of list of modules. The modules grouped in the same list are adjacents and have the same `qubits_support`

**2. Adapted the method `merged_unitary()` to multiqbits operations.**
The method merge the unitary of the operations that are adjacent and have the same `qubit_support`

**3. Adapted the method `forward()`**
The method applies the list of merged unitaries in a sequential manner to the state

**4. Added test**
The test compares the state obtained with the forward method against the state obtained with calling the `apply_operators` function for each of the unmerged operators sequentially

### CODE REVIEW

**Comment by jpmoutinho** [comment]
Hi @ducthanh1991, thanks for this!

Can you please lint your code before committing? You can run `pre-commit run --all-files` and make sure all stages pass. It will make it easier to review :)

**Comment by ducthanh1991** [comment]
@dominikandreasseitz, sorry, I did not lint the code yet. I'll work on it after work.

**Comment by jpmoutinho** [comment]
Hi @ducthanh1991, let us know if you have any questions on this :)

**Comment by ducthanh1991** [comment]
> Hi @ducthanh1991, let us know if you have any questions on this :)

I have run precommit and adapted the code. Could you review it?

**Comment by dominikandreasseitz** [comment]
@ducthanh1991 can you fix the tests?

**Comment by awennersteen** [comment]
> @ducthanh1991 can you fix the tests?

@dominikandreasseitz from what I saw it was a flaky test that failed

**Comment by ducthanh1991** [comment]
> > @ducthanh1991 can you fix the tests?
> 
> @dominikandreasseitz from what I saw it was a flaky test that failed
> 
> Edit: So python 3.11 suceeded, but 3.9 and 3.10 failed, re-running.



> > @ducthanh1991 can you fix the tests?
> 
> @dominikandreasseitz from what I saw it was a flaky test that failed
> 
> Edit: So python 3.11 suceeded, but 3.9 and 3.10 failed, re-running.

Hello @awennersteen, @dominikandreasseitz @jpmoutinho ,

I ran the test on my local machine (python 3.10.13) and all four tests from the file ` tests/qadence/test_measurements/test_sample_expectation.py` succeeded. But obviously it is not an intermittent failures because you ran it 6 times and it all failed. What does the file test? I'll try to dig deeper on how my change affected the test.

**Comment by dominikandreasseitz** [comment]
> > > @ducthanh1991 can you fix the tests?
> > 
> > 
> > @dominikandreasseitz from what I saw it was a flaky test that failed
> > Edit: So python 3.11 suceeded, but 3.9 and 3.10 failed, re-running.
> 
> > > @ducthanh1991 can you fix the tests?
> > 
> > 
> > @dominikandreasseitz from what I saw it was a flaky test that failed
> > Edit: So python 3.11 suceeded, but 3.9 and 3.10 failed, re-running.
> 
> Hello @awennersteen, @dominikandreasseitz @jpmoutinho ,
> 
> I ran the test on my local machine (python 3.10.13) and all four tests from the file ` tests/qadence/test_measurements/test_sample_expectation.py` succeeded. But obviously it is not an intermittent failures because you ran it 6 times and it all failed. What does the file test? I'll try to dig deeper on how my change affected the test.

@ducthanh1991 its a flaky test, feel free to increase the ATOL (in a reasonable manner)

**Comment by awennersteen** [comment]
Hi @ducthanh1991,
Looks like our pipelines are all dying at the moment, we'll fiddle with the threshold to see what it should be but please to report back if you've thought of any way this change might have affected the test. These tests have been very flaky in the past on the pipelines so it may just be chance.

Thanks for participating!

**Review by awennersteen — APPROVED** [review]
lgtm

**Comment by ducthanh1991** [comment]
> Hi @ducthanh1991, Looks like our pipelines are all dying at the moment, we'll fiddle with the threshold to see what it should be but please to report back if you've thought of any way this change might have affected the test. These tests have been very flaky in the past on the pipelines so it may just be chance.
> 
> Thanks for participating!

No problem! I'll keep digging into if my changes impacted that test. BTW, I am sorry: I did not know about the unitary hack event, thought the `unitaryhack` tag was a description of your issues :| .

**Pull request merged**
