### PR TITLE
[Bug] Correct SimConfig syntax.

### LINKED ISSUE #408: [Bug] Qadence protocol ZNE test fails, requires SimConfig updates
Pulser backend written in qadence is using the following to create sim_config. Pulser has moved from using "_prob"  to "_rate" in their SimConfigs.  
`sim_config = {"noise": noise.protocol, noise.protocol + "_prob": noise_prob}`

The tests (ZNE) in qadence protocols are failing due to this with the following error

```
FAILED tests/test_zne.py::test_analog_zne_with_noise_levels[analog_block0-observable0-noise_probs0-depolarizing] - TypeError: SimConfig.__init__() got an unexpected keyword argument 'depolarizing_prob'
FAILED tests/test_zne.py::test_analog_zne_with_noise_levels[analog_block1-observable1-noise_probs1-dephasing] - TypeError: SimConfig.__init__() got an unexpected keyword argument 'dephasing_prob'
FAILED tests/test_zne.py::test_analog_zne_with_pulse_stretching[analog_block0-observable0-noise_probs0-depolarizing-param_values0] - TypeError: SimConfig.__init__() got an unexpected keyword argument 'depolarizing_prob'
```

Not sure if this is valid, but I think there should be feature tests included that fail when backend changes happen, so that wrappers written on it run smoothly.

### PR DESCRIPTION
**Pull request by Roland-djee**
Closes #408.

### CODE REVIEW

**Comment by rajaiitp** [comment]
Hey @Roland-djee , did you check if it fixes the ZNE test cases 😅. Do you think we should keep a test case on qadence for future updates that might happen on the pulser end?

**Review by rajaiitp — APPROVED** [review]

**Comment by rajaiitp** [comment]
>> > Hey @Roland-djee , did you check if it fixes the ZNE test cases 😅.
>> 
>> I am on it now.
> Tested with this fix locally, It works fine

**Comment by Roland-djee** [comment]
> Tested with this fix locally, It works fine

Because you've got a local Pulserv0.18.0 haven't you ?

**Comment by rajaiitp** [comment]
> Because you've got a local Pulserv0.18.0 haven't you ?
Yes, I do, I checked that its the latest release, so it should be fine right ? 😅

**Comment by Roland-djee** [comment]
>  Yes, I do, I checked that its the latest release, so it should be fine right ? 😅

For your local setting yes. However, to be effective for all users, Qadence should support Pulserv0.18.0 which might cause some upgrade issues. I am on that now.

**Comment by Roland-djee** [comment]
@dominikandreasseitz Is it fine with you ? If so, I'll merge and work on Renovate since it didn't pick up latest deps versions like Pulser.

**Comment by dominikandreasseitz** [comment]
> @dominikandreasseitz Is it fine with you ? If so, I'll merge and work on Renovate since it didn't pick up latest deps versions like Pulser.

@Roland-djee sure, but should we add some tests which ensure that this is actually functional across updates? same for your previous MR related to noise

**Comment by Roland-djee** [comment]
> @Roland-djee sure, but should we add some tests which ensure that this is actually functional across updates? same for your previous MR related to noise

Well, that should be Renovate's job, if configured correctly.

**Comment by dominikandreasseitz** [comment]
@Roland-djee i meant adding a unit test which tests this particular piece of code, meaning the simconfig in this MR, and the passing of the noise to `sample` in the previous one

**Comment by Roland-djee** [comment]
> @Roland-djee i meant adding a unit test which tests this particular piece of code, meaning the simconfig in this MR, and the passing of the noise to `sample` in the previous one

This can be done with Pulserv0.18.0 since it complies with new API. So I can add that test once Qadence supports it.

**Review by dominikandreasseitz — APPROVED** [review]
not sure about the details on the pulser side here tbh but lgtm

**Comment by Roland-djee** [comment]
> not sure about the details on the pulser side here tbh but lgtm

Simply the string keys to the simconfig have changed from `depolarization_prob` -> `depolarization_rate`.

**Pull request merged**
