### PR TITLE
[Bugfix] Fix cron schedule

### PR DESCRIPTION
**Pull request by Roland-djee**

### CODE REVIEW

**Comment by Roland-djee** [comment]
@dominikandreasseitz Is it fine with you ? It's only an attempt at seeing if the cron syntax works.

**Comment by dominikandreasseitz** [comment]
@Roland-djee sure i mean i am just a bit unhappy that we use MRs basically for debugging/testing code. but if there is no other way, lets merge it

**Review by dominikandreasseitz — APPROVED** [review]

**Comment by Roland-djee** [comment]
> @Roland-djee sure i mean i am just a bit unhappy that we use MRs basically for debugging/testing code. but if there is no other way, lets merge it

Indeed. Not the best way to do it but I don't know of any other way to test CI schedules. If you know, I'd be happy to hear really.

**Comment by Roland-djee** [comment]
Closing as superseded by the forthcoming renovate app.

**Pull request closed without merging**
